### ISSUE TITLE
'dart run custom_lint' is not  working 

### ISSUE THREAD

**Issue by komalkhatri08** [invertase/dart_custom_lint#181]
**Describe the bug**
when I try to run dart run custom_lint in my application terminal (VS Code)  it says no issues found. where as the 'Problem' window shows the custom lint issues.

**To Reproduce**
pubspec.yaml of my application:- 
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_launcher_icons: "^0.13.1"
  lint: ^2.1.2
  custom_lint: ^0.5.0
  my_awesome_lints: 
    path: ../my_awesome_lints/
```

analysis_option.yaml file looks like :- 
```
analyzer: 
  plugins:
    custom_lint
```

![image](https://github.com/invertase/dart_custom_lint/assets/136062872/c1056132-23c6-4afb-9d57-2cd55855d341)
above image shows no issues found when i run 'dart run custom_lint'
![image](https://github.com/invertase/dart_custom_lint/assets/136062872/24b739c4-1cb6-42ec-865e-aaa8ac02e237)
above image shows custom lint i wrote is displayed in Problem window and custom_lint.log file .

**Expected behavior**
'dart run custom_lint' on terminal should list custom_lint issues I wrote. 
my main goal is to prevent commit using git hooks if 'flutter analyze' and custom lint issues exist in code.

**Comment by rrousselGit** [comment]
Is there a chance you could make a git repository to reproduce this?

**Comment by komalkhatri08** [comment]
Hi Remi,

Sorry I cannot do that.

Thanks,
Komal

**Comment by komalkhatri08** [comment]
@rrousselGit  any update?

**Comment by SunlightBro** [comment]
```yaml
analyzer: 
  plugins:
    custom_lint
```

is not valid YAML syntax, please check the [README](https://pub.dev/packages/custom_lint#using-our-custom-lint-package-in-an-application) or the official [YAML spec](https://yaml.org/spec/1.2.2/)

Instead it should be:
```yaml
analyzer: 
  plugins:
    - custom_lint
```

Also please for the future:
- Create a **minimal** reproducible code sample
  - remove **everything** else that is not needed to reproduce the issue
- Don't push it as a zip
- "**@.rrousselGit** any update?", in FOSS you should ask for help an not demand it.
  - Maybe thats just me (as a non-native english-speaker), that I interpret this as disrespectful.

This issue can be closed.
