### ISSUE TITLE
Error when removing Flutter dependencies from pubspec.yaml in specific modules

### ISSUE THREAD

**Issue by kensamare** [invertase/dart_custom_lint#238]
I have the following structure in a project.
```
- project
  - packages
    - data
    - domain
    - state
```

Added to pubspec.yaml for all packages:
```
custom_link: 0.6.2
my_lint: 1.0.0
```

And if you remove from one package all dependencies related to flutter, for example domain:

```
name: domain
description: "Domain"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

dev_dependencies:
  custom_lint: 0.6.2
  my_lint: 1.0.0
```

And in other packages I leave everything as is, then I get an error:
```
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
ProcessException: No such file or directory
  Command: flutter pub get
```

Sometimes:
```
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
UnimplementedError
```
However, this problem is observed only in Android Studio, when using VS Code this problem is not observed

**Comment by rehlma** [comment]
I had the same error with a slightly different setup.
```
- project/package
  - lib
  - analysis_options.yaml
  - pubspec.yaml
  - package_1
    - lib
    - analysis_options.yaml
    - pubspec.yaml
  - my_lint
    - lib
    - pubspec.yaml
    - example
      - lib
      - analysis_options.yaml
      - pubspec.yaml
```

At first I added `my_lint` to the `root`, `package_1` and `example` package like this and I always got that error with IntelliJ.
```
dev_dependencies:
  custom_lint: 0.6.2
  my_lint:
    path: ./my_lint
```
and
```
analyzer:
  plugins:
    - custom_lint
```

Then I noticed that the issues is solved once I ensure that the analyzer plugin is set **just once in my root package** and not in every `analysis_options.yaml` And only add the dev_dependencies to all packages where you intend to use your `my_lint`

I hope this might help you.
