### ISSUE TITLE
(Possible) Memory Leaks

### ISSUE THREAD

**Issue by MichaelDarkMostIo** [invertase/dart_custom_lint#248]
It looks like `custom_lint_client` process is consuming more RAM than the whole `analysis_server`.

![Screenshot 2024-05-07 at 13 58 51](https://github.com/invertase/dart_custom_lint/assets/127096658/7a169c4e-d482-4f99-b859-bf5a4075ec69)

Not sure what kind of related info I should provide for the issue, but it must be either a lack of optimization or memory leaks problem.

**Comment by EArminjon** [comment]
Got same observation, didn't know why but when enabling this plugin i got a lot heavy CPU usage.

**Comment by victor-tinoco** [comment]
I'm running the same as well. This consumes the CPU and slows my laptop down in a way I'm kinda obligated to open the _Activity Monitor_ and just kill it all the time.

**Comment by victorcatn** [comment]
This issue was slowing significantly my IDE, just navigating with cmd+clic was taking tens of seconds and saving dart files was taking minutes if not crashing.
It happened in multiple projects using custom_lint and riverpod_lints.
I tried with a new computer with a clean install and the issue happened again.
For now I had to disable custom_lint in all my projects to get a normal development flow

**Comment by amrgetment** [comment]
I confirmed same issue but it wasn’t there 1 month ago

**Comment by rrousselGit** [comment]
Do you have any error in the custom_lint.log or something?

**Comment by amrgetment** [comment]
No errors, I use those linters:

dev_dependencies:
  # Linters
  flutter_lints: ^4.0.0
  autoclose_lint: ^1.0.2
  custom_lint: ^0.6.4
  freezed_lint: ^0.0.2
  solid_lints: ^0.1.5


I use `prefer_match_file_name` from solid_lints but I don’t think it is related to the memory issue, and once I disable 
 # plugins:
 #  - custom_lint
no memory issues


[analysis_options.yaml.zip](https://github.com/user-attachments/files/16028800/analysis_options.yaml.zip)

**Comment by amrgetment** [comment]
I will activate it again and I will let you know if I got errors

**Comment by rrousselGit** [comment]
For what it's worth, I'm making significant changes to support analyzer 6.5.0.
Hopefully this should get better.

Still, in terms of memory, it's always going to consume quite a bit.

Anyway note that the memory issue could be coming from a specific plugin. For instance, it could be that riverpod_lint is the problem. I could see how that happens, as it does a lot of caching.

**Comment by amrgetment** [comment]
macros will improve build_runners
what would be the feature in the dart that could improve the analyzer?

**Comment by rrousselGit** [comment]
Not a Dart feature but an analyzer feature. Plugins are getting a rework to solve memory issues.

**Comment by EArminjon** [comment]
What about CPU usage 👀 ?

Thanks for your amazing package ❤️

**Comment by rrousselGit** [comment]
Depends. Note that there could always be a bug in any of the packages.

For example I'm aware of at least one performance issue caused by some form of delayed infinite loop in riverpod_lint. I'm working on fixing this at the moment.

**Comment by yasht01** [comment]
Our dev team has also been facing this issue after upgrading to Flutter 3.24 version.

**Comment by buncis** [comment]
<img width="1600" height="390" alt="Image" src="https://github.com/user-attachments/assets/26996a47-eab5-48f9-afb7-2f3d4ef2a908" />

I find it too high too

I'm opening this repo btw https://github.com/lucavenir/go_router_riverpod/

**Comment by MichaelDarkMostIo** [comment]
> Do note that I do not plan on working significantly on custom_lint.
> 
> An official google implementation is in beta. It's preferable to migrate to the official solution instead.

I will do my best to either help you find motivation or pick it up to maintain 🙏🏻

What should be my first steps if I would like to get to the bottom of things and become a maintainer? Submit a PR with a memory leak fix? 😅

**Comment by Vonarian** [comment]
My custom_lint.log can some times reach 20+ MBs, these two maybe be useful:

[custom_lint.log 11-09-21-266 AM.log](https://github.com/user-attachments/files/23494573/custom_lint.log.11-09-21-266.AM.log)

[custom_lint 9.54.46 AM.log.zip](https://github.com/user-attachments/files/23494578/custom_lint.9.54.46.AM.log.zip)
```yaml
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: true # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors: true # Uncomment to enable the `prefer_const_constructors` rule
    prefer_const_literals_to_create_immutables: true # Uncomment to enable the `prefer_const_literals_to_create_immutables` rule
    prefer_const_constructors_in_immutables: true # Uncomment to enable the `prefer_const_constructors_in_immutables` rule
    prefer_final_fields: true # Uncomment to enable the `prefer_final_fields` rule
    prefer_final_locals: true # Uncomment to enable the `prefer_final_locals` rule
    prefer_is_empty: true # Uncomment to enable the `prefer_is_empty` rule
    prefer_is_not_empty: true # Uncomment to enable the `prefer_is_not_empty` rule
    prefer_relative_imports: true # Uncomment to enable the `prefer_relative_imports` rule
    unawaited_futures: true # Uncomment to enable the `unawaited_futures` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  plugins:
    - custom_lint
  exclude: [lib/**.old, docs/**, ./**.md, ./**.log]
dcm:
  rules:
    - always-remove-listener: true
    - avoid-global-state: true
    - avoid-unnecessary-setstate: true
    - avoid-unused-parameters: true
    - avoid-unnecessary-type-casts: true
    - avoid-unnecessary-type-assertions: true
    - prefer-const-border-radius: true
    - prefer-last: true
    - prefer-first: true
    - avoid-nullable-tostring: true

custom_list:
  debug: false
  verbose: false
```
