### ISSUE TITLE
Custom lint not working on Monorepo

### ISSUE THREAD

**Issue by hpelitebook745G2** [invertase/dart_custom_lint#267]
**Describe the bug**
I have a monorepo with a lot of packages, each package is either a Dart or Flutter project. I want to apply my custom lint at the very root so I don't need to tediously update all `pubspec.yaml` but it's not working.

**To Reproduce**

I've been reading the issues here but what worked for me is to apply:
```
dev_dependencies:
  custom_lint: ^0.6.4
  custom_lint_example_lint:
    path: ../example_lint
```
to each of the packages and I have more than 20. Is it even possible to apply once and analyze all the code in my monorepo? If so, I haven't found any instructions in the README. Please advise.

**Expected behavior**
Apply once, analyze anywhere
