### ISSUE TITLE
Support pub workspaces

### ISSUE THREAD

**Issue by dcharkes** [invertase/dart_custom_lint#329]
```yaml
resolution: workspace

dev_dependencies:
  repo_lint_rules:
    path: ../repo_lint_rules/
```

succeeds

```yaml
resolution: workspace

dev_dependencies:
  repo_lint_rules: 0.1.0-wip
```

fails with the following error

```
+dart analyze --fatal-infos pkgs/code_assets pkgs/data_assets pkgs/hooks pkgs/hooks_runner pkgs/json_syntax_generator pkgs/native_toolchain_c pkgs/repo_lint_rules
Analyzing code_assets, data_assets, hooks, hooks_runner, json_syntax_generator, native_toolchain_c, repo_lint_rules...

An error occurred while executing an analyzer plugin: Exception: Failed to run "pub get" in the client project:
Resolving dependencies...

Because custom_lint_client depends on repo_lint_rules any which doesn't exist (could not find package repo_lint_rules at https://pub.dev), version solving failed.
```

The workspace pubspec contains both `repo_lint_rules` which is a custom lint and the package referring to the custom lint.

Workaround: Use path dependencies for now.
