### ISSUE TITLE
Custom lints not showing lints at all

### ISSUE THREAD

**Issue by Biplab-Dutta** [invertase/dart_custom_lint#36]
So, I was working on some lints and everything was fine until yesterday. I created my lint, had it working and then I went saved my work, and went to bed. The next day when I tried opening the same project, the lints are not getting displayed at all. I had other lint projects too and none of them are working. I have all the `dependencies` and `dev_dependencies` properly configured.

**Comment by Biplab-Dutta** [comment]
After taking a look at the internals of `custom_lint` package, I saw an error in the `analyzer_plugin.dart` file.
![image](https://user-images.githubusercontent.com/63902683/193470183-f6317b7e-96a6-4f75-9ac2-040e81f23417.png)

The error message says
```
The named parameter 'cacheTime' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'cacheTime'.
```
Can this be the reason why the lints which were working fine stopped getting displayed?

**Comment by rrousselGit** [comment]
Run `pub upgrade` and this should be fixed now.

**Comment by Biplab-Dutta** [comment]
@rrousselGit Looks like the issue still exists.
This is the `pubspec.yaml` of my sample lint project.
```yaml
name: sample_lints
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  analyzer: ^4.6.0
  analyzer_plugin: ^0.10.0
  custom_lint_builder: ^0.0.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
```
On running `dart run custom_lint`, I am getting proper logs
```bash
lib/hello_world.dart:5:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
lib/hello_world.dart:7:7 • Classes extending Mock or Fake should be at the bottom. • move_mocks_and_fakes_to_the_bottom_of_the_file
lib/hello_world.dart:9:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
lib/second_file.dart:3:7 • Classes extending Mock or Fake should be private and be at the bottom of the file. • create_private_mock_or_fake_class_and_move_declaration_to_bottom
```
However, the IDE doesn't show any warnings.
![image](https://user-images.githubusercontent.com/63902683/193847110-59dfcdfa-2374-4e29-ac03-d07e03aedbfd.png)

The `analyzer` and `analyzer_plugin` can be upgraded to ^5.1.0 and ^0.11.2 respectively. But `custom_lint` still depends on older version.
