### ISSUE TITLE
When installing along with `flutter_hooks_lint_plugin`, when trying to add `custom_lint` to analyzer plugins, `Multiple plugins can't be enabled` error occurs

### ISSUE THREAD

**Issue by satvikpendem** [invertase/dart_custom_lint#78]
**Describe the bug**
Multiple plugins apparently can't be added to `analysis_options.yaml` if we're using both `flutter_hooks_lint_plugin` and `custom_lint`.

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

Add `flutter_hooks` and `flutter_hooks_lint_plugin` as well as `riverpod_lint` and `custom_lint` to `pubspec.yaml`, and when you try to add `custom_lint` to `analysis_options.yaml`, there is a warning stating:

```
Multiple plugins can't be enabled.
Remove all plugins following the first, 'flutter_hooks_lint_plugin'. dart(multiple_plugins)
```

**Expected behavior**
Both should work together.

**Comment by rrousselGit** [comment]
Did you add `custom_lint`to your analysis_options.yaml twice?

You only need to add it once. It'll enable both plugins at once.

**Comment by satvikpendem** [comment]
I don't think I added it twice, here is my entire `analysis_options.yaml`:

```yaml
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
  plugins:
    - flutter_hooks_lint_plugin
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```

With the warning:

![image](https://user-images.githubusercontent.com/42670561/218343284-adce1816-ce86-4a84-a5d4-bf2a9899e7aa.png)
